version: "3.9"

services:
      spark-app:
        build: .
        container_name: pyspark-dev
        volumes:
          - .:/app
        working_dir: /app
        tty: true
        ports:
          - "8888:8888"    # Jupyter
        env_file:
          - .env 